### ISSUE TITLE
Typo (I believe on Readme)

### ISSUE THREAD

**Issue by diasdavid** [ipfs/contributors#2]
> # Update the dns record for libp2p to point to the new ipfs hash.
https://github.com/ipfs/contribs#deploy

Is this correct?

**Comment by alanshaw** [comment]
Yes that is incorrect. I have take out the publish to domain smarts as it isn't needed.

**Comment by alanshaw** [comment]
Resolved here https://github.com/ipfs/contributors/pull/7

**Comment by diasdavid** [comment]
Thank you @alanshaw :)
